<?php if(count($this->getItems())): ?>
<div class="crosssell"  style="margin-bottom: 15px;">
    <div class="title">
        <h2><?php echo $this->__('Related Items') ?></h2>
    </div>

    <script type="text/javascript">
        jQuery(document).ready(function() {
            jQuery('#crosssell-carousel').jcarousel();
        });
    </script>
    <ul id="crosssell-carousel" class="jcarousel-skin-servu-crosssell">
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="item">
            <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(142); ?>" width="142" height="142" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
            <div class="product-details">
                <h3 class="product-name" style="height: 55px;"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h3>
                <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_item); ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript">decorateList('block-related', 'none-recursive')</script>
</div>
<?php endif; ?>