<script type="text/javascript">
function openNewImportWindow(url) {
    dialog_import_window = Dialog.info('', {
        draggable:true,                                              
        resizable:true,                                              
        closable:true,                                               
        className:"magento",
        windowClassName:"popup-window",
        title:"New import item",
        top:50,
        width:950,
        height:250,
        zIndex:10,
        recenterAuto:false,
        hideEffect:Element.hide,
        showEffect:Element.show,
        id:"new-import"
    });
    new Ajax.Updater($$('#new-import_content #modal_dialog_message')[0], url, {evalScripts: true});
}

function saveNewImportItem(url)
{
    new Ajax.Request(url, {
        parameters: $('import_item_form').serialize(true),
        onSuccess: function(response) {
            var json = response.responseText.evalJSON();
            if (json) {
                dialog_import_window.close();
                if (typeof(shoppingfeeds_feed_bing_list_codesJsObject) == 'object') {
                    shoppingfeeds_feed_bing_list_codesJsObject.reload();
                }
                if (typeof(shoppingfeeds_feed_thefind_list_codesJsObject) == 'object') {
                    shoppingfeeds_feed_thefind_list_codesJsObject.reload();
                }
                for(var b in window) { 
                if(window.hasOwnProperty(b)) console.log(b); 
                }
            }
        }
    });
}

function closeNewImportItem()
{
    dialog_import_window.close();
}
</script>

<style>
    .grid tr.filter select { width: 100% !important; }
</style>
