<?php
$_helper          =  Mage::helper('catalogsearch');
$_value           = $_helper->getEscapedQueryText();
//$_currentCategory = Mage::getSingleton('core/app')->getRequest()->getParam('cat');
$_currentIndex    = Mage::getSingleton('core/app')->getRequest()->getParam('index');
//$_filterType      = $this->getFilterType();
$_url             = $this->getAjaxUrl();
?>
<form class="searchautocomplete UI-SEARCHAUTOCOMPLETE" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get"
    data-tip="<?php echo $this->__(Mage::getStoreConfig('searchautocomplete/general/tip')) ?>"
    data-url="<?php echo $_url ?>"
    data-minchars="<?php echo Mage::getStoreConfig('searchautocomplete/general/min_chars') ?>"
    data-delay="<?php echo Mage::getStoreConfig('searchautocomplete/general/delay') ?>">

    <div class="nav">
        <input class="input-text UI-SEARCH" type="text" autocomplete="off" name="<?php echo $_helper->getQueryParamName() ?>" value="<?php echo $_helper->getEscapedQueryText() ?>" maxlength="<?php echo $_helper->getMaxQueryLength() ?>" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><?php echo $this->__('Search') ?></button>
        <div class="searchautocomplete-loader UI-LOADER" style="display:none;"></div>
    </div>
    <div style="display:none" class="searchautocomplete-placeholder UI-PLACEHOLDER"></div>
</form>